FIRST_CARD_IN_HAND = 0
SECOND_CARD_IN_HAND = 1
THIRD_CARD_IN_HAND = 2
FOURTH_CARD_IN_HAND = 3
FIFTH_CARD_IN_HAND = 4

NONE = -1
OPPONENT = 0
SECOND_CHARACTER_FROM_ACTIVE_PERSPECTIVE = 1
THIRD_CHARACTER_FROM_ACTIVE_PERSPECTIVE = 2
FOURTH_CHARACTER_FROM_ACTIVE_PERSPECTIVE = 3
FIFTH_CHARACTER_FROM_ACTIVE_PERSPECTIVE = 4

THE_COIN = 0
WISP = 1
ARGENT_SQUIRE = 2
BILEFIN_TIDEHUNTER = 3
ANCIENT_WATCHER = 4
SPELLBREAKER = 5
LOOT_HOARDER = 6
OOZE = 7

PLAYER_1_DECK = [LOOT_HOARDER, BILEFIN_TIDEHUNTER, ANCIENT_WATCHER, ARGENT_SQUIRE, LOOT_HOARDER, BILEFIN_TIDEHUNTER, SPELLBREAKER, WISP, SPELLBREAKER, WISP, ANCIENT_WATCHER, ARGENT_SQUIRE]
PLAYER_2_DECK = [LOOT_HOARDER, SPELLBREAKER, ARGENT_SQUIRE, ANCIENT_WATCHER, SPELLBREAKER, ANCIENT_WATCHER, BILEFIN_TIDEHUNTER, LOOT_HOARDER, ARGENT_SQUIRE, WISP, BILEFIN_TIDEHUNTER, WISP]

PLAYER_START_HEALTH = 30